-- Cinema House - starter movie catalog.
-- Generated from src/data/movies.js. Posters for these films are bundled with
-- the website, so poster_url stays empty here.
-- Screenings are scheduled in the admin. Safe to run more than once.

insert into public.movies
  (id, title, genres, age_rating, duration, year, score, director, cast_members, format, halls, status, release_date, tagline, synopsis, art, sort_order)
values
  ('spider-man-brand-new-day', 'Spider-Man: Brand New Day', array['Action', 'Adventure', 'Sci-Fi']::text[], '12+', 130, 2026, 8.2, 'Destin Daniel Cretton', array['Tom Holland', 'Sadie Sink', 'Jon Bernthal']::text[], array['IMAX', '2D']::text[], array[]::text[], 'now-showing', null, 'Every day is a new beginning.', 'With his old life erased and no one left who remembers his name, Peter Parker starts again from nothing - and finds that the city still needs somebody to look out for it.', '{"from":"#8a1220","to":"#0b0508","accent":"#ff4d5a","motif":"city"}'::jsonb, 0),
  ('insidious-chapter-6', 'Insidious: Chapter 6', array['Horror', 'Mystery', 'Thriller']::text[], '18+', 104, 2026, 7.1, 'Jacob Chase', array['Patrick Wilson', 'Rose Byrne', 'Ty Simpkins']::text[], array['2D']::text[], array[]::text[], 'now-showing', null, 'The Further is never finished with you.', 'A family that thought it had left the Further behind finds the door open again, and learns that what waits on the other side has been counting the years with them.', '{"from":"#3a0d18","to":"#080405","accent":"#ff4d4d","motif":"signal"}'::jsonb, 1),
  ('the-odyssey', 'The Odyssey', array['Adventure', 'Drama', 'Fantasy']::text[], '12+', 150, 2026, 8.5, 'Christopher Nolan', array['Matt Damon', 'Anne Hathaway', 'Tom Holland']::text[], array['IMAX', '2D']::text[], array[]::text[], 'now-showing', null, 'The long way home.', 'Ten years after the war ends, a king still has not reached his own shore - and the sea, the gods and his own crew all have reasons to keep him from it.', '{"from":"#123a6b","to":"#060b14","accent":"#4ea8ff","motif":"waves"}'::jsonb, 2),
  ('minions-and-monsters', 'Minions & Monsters', array['Animation', 'Family', 'Comedy']::text[], '6+', 96, 2026, 7.8, 'Kyle Balda', array['Pierre Coffin', 'Steve Carell', 'Taraji P. Henson']::text[], array['2D']::text[], array[]::text[], 'now-showing', null, 'Small crew. Big problem.', 'When the creatures under the bed turn out to be real, and unionised, the little yellow crew has to decide whose side it is on before the whole city finds out.', '{"from":"#c9a227","to":"#171006","accent":"#ffd93d","motif":"bubbles"}'::jsonb, 3),
  ('fall-2-deadpoint', 'Fall 2: Deadpoint', array['Thriller', 'Survival']::text[], '16+', 101, 2026, 7.2, 'Scott Mann', array['Grace Caroline Currey', 'Virginia Gardner', 'Mason Gooding']::text[], array['IMAX', '2D']::text[], array[]::text[], 'now-showing', null, 'One move left.', 'A climb that was meant to close the book on the last one strands two friends on a face with no way down, no signal and a storm coming in behind them.', '{"from":"#1d3b4a","to":"#0a1013","accent":"#7fd4e8","motif":"ruins"}'::jsonb, 4),
  ('inside-out-2', 'Inside Out 2', array['Animation', 'Family', 'Comedy']::text[], '6+', 100, 2024, 8.1, 'Kelsey Mann', array['Amy Poehler', 'Maya Hawke', 'Kensington Tallman']::text[], array['2D']::text[], array[]::text[], 'now-showing', null, 'Make room for new feelings.', 'Riley is a teenager now, and headquarters is suddenly crowded: a whole crew of brand new emotions moves in and takes over the control panel.', '{"from":"#5a2f9a","to":"#12061f","accent":"#ffd34d","motif":"bubbles"}'::jsonb, 5),
  ('john-wick-4', 'John Wick: Chapter 6', array['Action', 'Crime', 'Thriller']::text[], '16+', 169, 2024, 8, 'Chad Stahelski', array['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgard']::text[], array['IMAX', '2D']::text[], array[]::text[], 'now-showing', null, 'No way back. One way out.', 'With a bounty on his head that keeps climbing, John Wick takes his fight against the High Table from New York to Paris, Osaka and Berlin.', '{"from":"#2a1030","to":"#0a0710","accent":"#ff5470","motif":"neon"}'::jsonb, 6),
  ('dune-part-two', 'Dune: Part Two', array['Sci-Fi', 'Adventure']::text[], '12+', 166, 2024, 8.7, 'Denis Villeneuve', array['Timothee Chalamet', 'Zendaya', 'Rebecca Ferguson']::text[], array['IMAX', '2D']::text[], array[]::text[], 'now-showing', null, 'Long live the fighters.', 'Paul Atreides joins the Fremen and walks the narrow path between revenge, prophecy and the future he is desperate to avoid.', '{"from":"#8a5a20","to":"#140d08","accent":"#f2c879","motif":"dunes"}'::jsonb, 7),
  ('shaun-the-sheep-mossy-bottom', 'Shaun the Sheep: The Beast of Mossy Bottom', array['Animation', 'Family', 'Comedy']::text[], '6+', 87, 2026, 7.9, 'Steve Cox', array['Justin Fletcher', 'John Sparkes', 'Kate Harbour']::text[], array['2D']::text[], array[]::text[], 'coming-soon', '2026-10-16'::date, 'Something is out there. Probably.', 'When something starts flattening the crops at night, the flock sets out to catch the beast of Mossy Bottom - and discovers the farm has been keeping a secret of its own.', '{"from":"#3f6d3a","to":"#0a1109","accent":"#c8e86b","motif":"bubbles"}'::jsonb, 8),
  ('a-talent-for-murder', 'A Talent for Murder', array['Thriller', 'Crime', 'Mystery']::text[], '16+', 108, 2026, 7.4, 'Elena Marsh', array['Rebecca Hall', 'Daniel Kaluuya', 'Sophie Okonedo']::text[], array['2D']::text[], array[]::text[], 'coming-soon', '2026-10-23'::date, 'Everyone is good at something.', 'A quiet copy editor notices a pattern in the manuscripts crossing her desk, and realises one of the writers has been confessing to something nobody has reported yet.', '{"from":"#2b1030","to":"#080510","accent":"#c47dff","motif":"signal"}'::jsonb, 9),
  ('klara-and-the-sun', 'Klara and the Sun', array['Drama', 'Sci-Fi']::text[], '12+', 116, 2026, 7.7, 'Taika Waititi', array['Jenna Ortega', 'Amy Adams', 'Steve Buscemi']::text[], array['2D']::text[], array[]::text[], 'coming-soon', '2026-10-23'::date, 'She was made to watch.', 'An artificial friend waiting in a shop window is chosen by a girl who is quietly ill, and sets out to save her using the only power she believes in - the sun.', '{"from":"#8a6a1f","to":"#100c06","accent":"#ffd977","motif":"dunes"}'::jsonb, 10),
  ('wildwood', 'Wildwood', array['Animation', 'Adventure', 'Fantasy']::text[], '6+', 104, 2026, 7.6, 'Travis Knight', array['Carey Mulligan', 'Mahershala Ali', 'Angela Bassett']::text[], array['2D']::text[], array[]::text[], 'coming-soon', '2026-10-23'::date, 'Nobody goes in. Nobody comes back.', 'When her baby brother is carried off by a murder of crows into the woods nobody in the city will talk about, a girl crosses the boundary and finds a country at war with itself.', '{"from":"#1f4a2c","to":"#070f0a","accent":"#8fe08a","motif":"ruins"}'::jsonb, 11),
  ('borderlands', 'Borderlands', array['Action', 'Sci-Fi', 'Comedy']::text[], '16+', 108, 2026, 6.4, 'Eli Roth', array['Cate Blanchett', 'Kevin Hart', 'Jamie Lee Curtis']::text[], array['2D']::text[], array[]::text[], 'coming-soon', '2026-10-30'::date, 'Bad guys. Worse planet.', 'A wanted bounty hunter returns to the trash planet she swore she would never see again, and picks up the worst possible crew on the way.', '{"from":"#7a1f4d","to":"#120510","accent":"#ffbf47","motif":"neon"}'::jsonb, 12),
  ('harbor-lights', 'Harbor Lights', array['Drama', 'Music']::text[], '12+', 121, 2026, 8.2, 'Nadia Okonjo', array['Sam Reyes', 'Aria Delgado', 'Femi Adeyemi']::text[], array['2D']::text[], array[]::text[], 'coming-soon', '2026-11-06'::date, 'Every port has a song.', 'A dock worker with a borrowed trumpet plays his way through one long winter and accidentally becomes the voice of his whole harbor town.', '{"from":"#123a5c","to":"#060c12","accent":"#ffd28a","motif":"waves"}'::jsonb, 13)
on conflict (id) do nothing;
